### ISSUE TITLE
ob and obj : Need as "ob" object and hero "obj" object which one is the good one ?

### ISSUE THREAD

**Issue by Shiftane** [LocalHero-swiss/centralherorepo#17]
https://github.com/LocalHero-swiss/centralherorepo/blob/0993d8219482946588e3600a371455daabed4096/handlers/requests.js#L38

https://github.com/LocalHero-swiss/centralherorepo/blob/0993d8219482946588e3600a371455daabed4096/handlers/heroes.js#L34

**Comment by bichettek** [comment]
Indeed, now it's aligned
