### ISSUE TITLE
Create a demand for beeing a Hero

### ISSUE THREAD

**Issue by Shiftane** [LocalHero-swiss/centralherorepo#33]
Create a route 
POST
/register/demand

**Request :**
Fields in body :
```
Full name (string)
phone number (string)
email (string)
image passport back (base64)
image passport front (base64)
image selfy (base64)
```

```
{
  _id : <auto>,
 fullName : <string, max 100>,
 email : <string, email_validator>,
 phone : <string, phone_validator>,
 frontID : <base64_image>,
 backID : <base64_image>,
 selfy : <base64_image>
}
```

**Response**
_Success_
```
{
 status : "SUCCESS"
 return : {
   _id : <from document>
 }
}
```
_Error_
```
{
 status : "ERROR"
 return : {
   message : <messageError>
 }
}
```
**What is the behaviour**
1. Insert a document in collection "demand"
document structure : 
```
{
  _id : <auto>,
 fullName : <from request>,
 email : <from request>,
 phone : <from request>,
 frontID : <from request>,
 backID : <from request>,
 selfy : <from request>,
 creationDate : <now>,
}
```
2. Send a formatted message to slack
Find url here : https://localheroswiss.slack.com/services/B01J32N3E3S?added=1
Url must be set in the server ENV variable.

**Comment by bichettek** [comment]
Should we use /heroes/create instead ? 
If so we need to remove the mandatory fields and maybe add this logic when we try to fetch heroes

**Comment by Shiftane** [comment]
we need to do something stateless for this approval process

**Comment by Shiftane** [comment]
> Should we use /heroes/create instead ?
> If so we need to remove the mandatory fields and maybe add this logic when we try to fetch heroes

if we create a hero, we have to modify also the filtering when matching or finding. Don't think it's a good idea. What do you think ?

Then the hero/approve could add an approbation_date
Then when user login, we validate this is a validated user with approbation_date and phone_number. (it's like having a user table and the hero link to user)

**Comment by Shiftane** [comment]
@bichettek 
Create a message with actions possible :
https://api.slack.com/messaging/interactivity
This is the endpoint to send a message on mobile-app channel : 
https://localheroswiss.slack.com/services/B01J32N3E3S?added=1
And for the button
https://api.slack.com/tutorials/intro-to-message-buttons

**Comment by bichettek** [comment]
Route created : /heroes/createApproval.
Exemple in postman
