### ISSUE TITLE
Request: get all heroes

### ISSUE THREAD

**Issue by Ruijan** [LocalHero-swiss/centralherorepo#8]
**Mandatory fields**
* Location: --> you shouldn't be able to retrieve all heroes in database
  * Country
  * ZIP Code

**Optional fields**
* maximum distance
* number of heroes returned

**Functionality**
* return all heroes in the area.
* sort them by distance to zip code
* limit number of heroes returned to 100 max

**Comment by Shiftane** [comment]
Thanks Julien, in your mind, we will put the matching logic in this route ?
